# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yellow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import random
import sys

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_yellow(object):
    def setupUi(self, yellow):
        yellow.setObjectName("yellow")
        yellow.resize(643, 513)
        self.centralwidget = QtWidgets.QWidget(yellow)
        self.centralwidget.setObjectName("centralwidget")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(270, 230, 75, 23))
        self.start.setObjectName("start")
        yellow.setCentralWidget(self.centralwidget)

        self.retranslateUi(yellow)
        QtCore.QMetaObject.connectSlotsByName(yellow)

    def retranslateUi(self, yellow):
        _translate = QtCore.QCoreApplication.translate
        yellow.setWindowTitle(_translate("yellow", "yellow"))
        self.start.setText(_translate("yellow", "старт"))
